### PR TITLE
Bug/2

### LINKED ISSUE #2: Incorrect digit grouping
Value: 80800000
Precision: Hundred Thousand
Expected: 80,800,000.00
Actual: 808,00000.00

Issue came from https://github.com/ecksbee/telefacts/issues/86

### LINKED ISSUE #4: Test Case Review
this test case: https://github.com/joshuanario/digits/blob/d391bf4b7f99bfce9b994f8104f9082715491da2/digits_test.go#L77-L92

`sigFigs` and `nonSigFigs` calculate as expected. The expected `strOut` is "77,190,000.00", with `precision` requested at the Millions. Is this actually expected, or should it be "77,000,000.00"?

if it is supposed to be as shown, then what is the intent with the first test case here: https://github.com/joshuanario/digits/blob/d391bf4b7f99bfce9b994f8104f9082715491da2/digits_test.go#L29-L44

Is exact precision expected in the integer part of the value, while the fractional part is rounded unless precision is specified in the tenths/hundredths?

This is a pretty critical distinction that isn't obvious from terminology alone, and should probably be clarified in the readme, if this is some non-standard implementation w/ regard to XBRL.

### PR DESCRIPTION
**Pull request by RourkeDawson**
intended to address issue #2. 

### At Time of Draft
- initial introduction of test case to replicate bug depicted in #2.
- modification of `digits_test.go` for clarity
- fix bad test case mentioned in #4.
### Before Review
- variable names/references updated, by request in PR
- `computeString()` function for generating the string expected from the calculated significant (and non-significant) figures
- `computeComponents()` function that generates the head, core, and tail components from the formatted string, using the significant figure as reference.

Benchmark for [main](https://github.com/joshuanario/digits/tree/main): 
```
goos: windows
goarch: amd64
pkg: github.com/joshuanario/digits
cpu: 13th Gen Intel(R) Core(TM) i7-1360P
BenchmarkSigFigs
BenchmarkSigFigs-16        14472             83270 ns/op
PASS
```
- 14472 op * 83270 ns/op = 1,204,968,240 ns (1.2 seconds per operation)

Benchmark for [bug/2](https://github.com/joshuanario/digits/tree/bug/2): 
```
goos: windows
goarch: amd64
pkg: github.com/joshuanario/digits
cpu: 13th Gen Intel(R) Core(TM) i7-1360P
BenchmarkSigFigs
BenchmarkSigFigs-16        22197             54014 ns/op
PASS
```
- 22197 op * 54014 ns/op = 1,198,560,758 ns (1.2 seconds per operation)

In terms of nanoseconds per operation, the bug branch is slightly more efficient, as it has a lower value. However, the difference is minuscule small. There's likely room to trim some functionality and combine efforts.

### CODE REVIEW

**Review by joshuanario — CHANGES_REQUESTED** [review]
Benchmarks won't run in `perf_test.go`.

Ensure benchmarks still runs, and check for any performance deficit introduced.  Be prepared to justify the PR if there are any performance deficit.

File: digits_test.go [hunk 1]
```diff
@@ -6,251 +6,341 @@ import (
...
-		",000.00)",
-		"00",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.Tail()
-		if output != expectation {
+	for _, sut := range suts {
+		var expr = process(sut.stimulus)
+		uut := expr.Tail()
```
Comment (joshuanario) [inline digits_test.go]: `uut` should named `output`

File: digits_test.go [hunk 2]
```diff
@@ -6,251 +6,341 @@ import (
...
+		if uut != sut.output.tail {
```
Comment (joshuanario) [inline digits_test.go]: this should be 

```
if output != sut.expecation.tail {
    // failure logic
}
```

File: digits_test.go [hunk 3]
```diff
@@ -6,251 +6,341 @@ import (
...
-		"1,038,807.",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.Core()
-		if output != expectation {
+	for _, sut := range suts {
+		var expr = process(sut.stimulus)
+		uut := expr.Core()
+		if uut != sut.output.core {
```
Comment (joshuanario) [inline digits_test.go]: this should be

```
if output != sut.expecation.core {
```

`uut` is actually the "output" (or "response") of the sut given a stimulus

File: digits_test.go [hunk 4]
```diff
@@ -6,251 +6,341 @@ import (
...
-		"98",
-		"338,863",
-		"1,038,807.",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.Core()
-		if output != expectation {
+	for _, sut := range suts {
+		var expr = process(sut.stimulus)
```
Comment (joshuanario) [inline digits_test.go]: to clarify this even further:

`expr` is the "Software Under Test" or `sut`.  `suts` are actually a collection of test cases, which is a pair of one stimulus and one expectation.

My recommendation is this:
```
for _, case := range cases {
		var sut = process(case.stimulus)
		output := sut.Core()
		if output != case.expectation.core {
```

File: digits_test.go (hunk 1 above)
Comment (RourkeDawson) [reply digits_test.go]: resolved by bf4ed23

File: digits_test.go (hunk 2 above)
Comment (RourkeDawson) [reply digits_test.go]: resolved by bf4ed23

File: digits_test.go [hunk 5]
```diff
@@ -6,251 +6,341 @@ import (
...
-		"",
-		"",
-		"(",
-		"",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.Head()
-		if output != expectation {
+	for _, sut := range suts {
```
Comment (joshuanario) [inline digits_test.go]: Similar issue here.  See my previous comments about `cases`, `sut`, and `output`.

File: digits_test.go (hunk 3 above)
Comment (RourkeDawson) [reply digits_test.go]: resolved by bf4ed23

File: digits_test.go [hunk 6]
```diff
@@ -6,251 +6,341 @@ import (
...
-		"45,121,000.00",
-		"98,000.00",
-		"(338,863,000.00)",
-		"1,038,807.00",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.String()
-		if output != expectation {
+	for _, sut := range suts {
```
Comment (joshuanario) [inline digits_test.go]: Similar issue here. See my previous comments about cases, sut, and output.

File: digits_test.go [hunk 7]
```diff
@@ -6,251 +6,341 @@ import (
...
-		"000",
-		"000",
-		"000",
-		"",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.NonSigFigs()
-		if output != expectation {
+	for _, sut := range suts {
```
Comment (joshuanario) [inline digits_test.go]: Similar issue here. See my previous comments about cases, sut, and output.

File: digits_test.go [hunk 8]
```diff
@@ -6,251 +6,341 @@ import (
...
-		"45121",
-		"98",
-		"338863",
-		"1038807",
-	}
-	for i, expectation := range expectations {
-		sut := suts[i]
-		output := sut.SigFigs()
-		if output != expectation {
+	for _, sut := range suts {
```
Comment (joshuanario) [inline digits_test.go]: Similar issue here. See my previous comments about cases, sut, and output.

File: digitsGroup_test.go [hunk 9]
```diff
@@ -0,0 +1,76 @@
+package digits
+
+type Stimulus struct {
```
Comment (joshuanario) [inline digitsGroup_test.go]: Do not make this struct public within the `digits` package.  This will be included in the library's binary.

File: digitsGroup_test.go [hunk 10]
```diff
@@ -0,0 +1,76 @@
...
+	value               string
+	groupingCharRune    rune
+	groupingCharStr     string
+	ifSigFig            bool
+	fractionalPrecision Decimals
+}
+type Output struct {
```
Comment (joshuanario) [inline digitsGroup_test.go]: Do not make this struct public within the `digits` package.  This will be included in the library's binary.

File: digitsGroup_test.go [hunk 11]
```diff
@@ -0,0 +1,76 @@
...
+	triplified string
+	final      string
+}
+type SUT struct {
```
Comment (joshuanario) [inline digitsGroup_test.go]: Do not make this struct public within the `digits` package.  This will be included in the library's binary.

File: digits_test.go [hunk 12]
```diff
@@ -6,251 +6,341 @@ import (
 	"github.com/joshuanario/digits"
 )
 
-type stimulus struct {
-	p digits.Precision
-	v string
-	g rune
-	d digits.Decimals
+type Stimulus struct {
```
Comment (joshuanario) [inline digits_test.go]: Make sure testing structs are private.

File: digits_test.go [hunk 13]
```diff
@@ -6,251 +6,341 @@ import (
...
+	precision           digits.Precision
+	value               string
+	groupSeparator      rune
+	fractionalPrecision digits.Decimals
+}
+type Output struct {
```
Comment (joshuanario) [inline digits_test.go]: Make sure testing structs are private.

File: digits_test.go [hunk 14]
```diff
@@ -6,251 +6,341 @@ import (
...
+	sigFigs    string
+	nonSigFigs string
+	strOut     string
+	head       string
+	core       string
+	tail       string
+}
+type SUT struct {
```
Comment (joshuanario) [inline digits_test.go]: Make sure testing structs are private.

File: digits_test.go (hunk 4 above)
Comment (RourkeDawson) [reply digits_test.go]: addressed in bccb919. `testCase` and `testCases` used instead of `case` and `cases`, due to case being a reserved name in go

File: digits_test.go (hunk 5 above)
Comment (RourkeDawson) [reply digits_test.go]: addressed in bccb919. `testCase` and `testCases` used instead of `case` and `cases`, due to case being a reserved name in go

File: digits_test.go (hunk 6 above)
Comment (RourkeDawson) [reply digits_test.go]: addressed in bccb919. `testCase` and `testCases` used instead of `case` and `cases`, due to case being a reserved name in go

File: digits_test.go (hunk 7 above)
Comment (RourkeDawson) [reply digits_test.go]: addressed in bccb919. `testCase` and `testCases` used instead of `case` and `cases`, due to case being a reserved name in go

File: digitsGroup_test.go (hunk 9 above)
Comment (RourkeDawson) [reply digitsGroup_test.go]: 3cc05b7

File: digitsGroup_test.go (hunk 10 above)
Comment (RourkeDawson) [reply digitsGroup_test.go]: 3cc05b7

File: digitsGroup_test.go (hunk 11 above)
Comment (RourkeDawson) [reply digitsGroup_test.go]: 3cc05b7

File: digits_test.go (hunk 12 above)
Comment (RourkeDawson) [reply digits_test.go]: 3cc05b7

File: digits_test.go (hunk 13 above)
Comment (RourkeDawson) [reply digits_test.go]: 3cc05b7

File: digits_test.go (hunk 14 above)
Comment (RourkeDawson) [reply digits_test.go]: 3cc05b7

File: digits_test.go (hunk 8 above)
Comment (RourkeDawson) [reply digits_test.go]: addressed in https://github.com/joshuanario/digits/commit/bccb9198881484d18b62ea3e63ae9dd5f7bda76b. testCase and testCases used instead of case and cases, due to case being a reserved name in go

File: digits_test.go [hunk 15]
```diff
@@ -7,250 +7,334 @@ import (
...
-	p digits.Precision
-	v string
-	g rune
-	d digits.Decimals
+	precision           digits.Precision
+	value               string
+	groupSeparator      rune
+	fractionalPrecision digits.Decimals
+}
+type output struct {
```
Comment (joshuanario) [inline digits_test.go]: `type expectation struct {`

File: digits_test.go [hunk 16]
```diff
@@ -7,250 +7,334 @@ import (
...
-var stimuli = []*stimulus{
+var testCases = []*testCase{
+	{
+		stimulus: stimulus{
+			precision:           digits.Oneth,
+			value:               "0.99",
+			groupSeparator:      ',',
+			fractionalPrecision: digits.PreserveUpToHundredth,
+		},
+		output: output{
```
Comment (joshuanario) [inline digits_test.go]: `expectation: expectation{ `

File: digits_test.go [hunk 17]
```diff
@@ -7,250 +7,334 @@ import (
...
+			core:       "80,8",
+			tail:       "00,000.00)",
+		},
 	},
 	{
-		p: digits.Exact,
-		v: "1038807",
-		g: ',',
-		d: digits.PreserveUpToHundredth,
+		stimulus: stimulus{
```
Comment (joshuanario) [inline digits_test.go]: This is a good addition to the test coverage, but I would declare this out of scope of the current work item.

Comment out this test case with a TODO and a url to the reported bug like this:

```

	// {	//todo BUG <url to github issue here>
	// 	stimulus: stimulus{
	// 		precision:           digits.Tenth,
	// 		value:               "80800000.99090909090",
	// 		groupSeparator:      ',',
	// 		fractionalPrecision: digits.PreserveUpToHundredth,
	// 	},
	// 	output: output{
	// 		sigFigs:    "80800000.9",
	// 		nonSigFigs: "9",
	// 		strOut:     "80,800,000.99",
	// 		head:       "",
	// 		core:       "80,800,000.9",
	// 		tail:       "9",
	// 	},
	// },
```

File: digits_test.go [hunk 18]
```diff
@@ -7,250 +7,334 @@ import (
...
+			value:               "1038807",
+			groupSeparator:      ',',
+			fractionalPrecision: digits.PreserveUpToHundredth,
+		},
+		output: output{
+			sigFigs:    "1038807",
+			nonSigFigs: "",
+			strOut:     "1,038,807.00",
+			head:       "",
+			core:       "1,038,807.",
```
Comment (joshuanario) [inline digits_test.go:233]: Tis is currently failing.  Shipping a regression issue is not permissible in this project.

```
 go test -timeout 15s github.com/joshuanario/digits
--- FAIL: Test_Core (0.00s)
    digits_test.go:330: 1,038,807 != 1,038,807., 12
--- FAIL: Test_Tail (0.00s)
    digits_test.go:338: .00 != 00, 12
FAIL
FAIL    github.com/joshuanario/digits   0.245s
FAIL
```

Comment (RourkeDawson) [reply digits_test.go:233]: thanks. This isn't posted for review yet, so I'll comment again when it's actually ready for review.

File: digits.go [hunk 19]
```diff
@@ -6,41 +6,44 @@ type Expression struct {
...
-	core, err := computeCore(p, v, g, d)
+	stringOut, err := computeString(sigFigs, nonSigFigs, groupSeparator, decimalPrecision, ret.sign)
 	if err != nil {
 		return nil, err
 	}
-	ret.core = core
-	tail, err := computeTail(p, v, g, d)
+	ret.stringOut = stringOut
+	ret.head = computeHead(trunc)
+	//core, err := computeCore(significantPrecision, value, groupSeparator, decimalPrecision)
```
Comment (joshuanario) [inline digits.go]: Try this:


```

	var core, tail string
	if significantPrecision == Exact {
		core, err = computeCore(significantPrecision, value, groupSeparator, decimalPrecision)
		if err != nil {
			return nil, err
		}
		tail, err = computeTail(significantPrecision, value, groupSeparator, decimalPrecision)
	} else {
		core, tail, err = computeCoreTail(sigFigs, stringOut, groupSeparator)
	}
	if err != nil {
		return nil, err
	}
	ret.core = core
	ret.tail = tail
	return &ret, nil
```

File: digits_test.go (hunk 17 above)
Comment (RourkeDawson) [reply digits_test.go]: #7

Comment (joshuanario) [reply digits_test.go]: I'm going to clarify why this is out of scope.  Currently `telefacts` (an XBRL processor) is the major consumer of `digits`.  A numeric expression like this practically will never ever happen within the XBRL community.  This is a numeric value that mathematicians and scientists would come up with.  Therefore, fixing this is not a priority as this will never be seen as an XBRL numeric fact.

**Comment by RourkeDawson** [comment]
Benchmark for [main](https://github.com/joshuanario/digits/tree/main): 
- 14472 op * 83270 ns/op = 1,204,968,240 ns (1.2 seconds per operation)

Benchmark for [bug/2](https://github.com/joshuanario/digits/tree/bug/2): 
- 22197 op * 54014 ns/op = 1,198,560,758 ns (1.2 seconds per operation)

In terms of nanoseconds per operation, the bug branch is slightly more efficient, as it has a lower value. However, the difference is minuscule small. There's likely room to trim some functionality and combine efforts.

File: digits.go [hunk 20]
```diff
@@ -6,41 +6,44 @@ type Expression struct {
...
-	ret.head = computeHead(value)
-	core, err := computeCore(p, v, g, d)
+	stringOut, err := computeString(significantPrecision, sigFigs, nonSigFigs, groupSeparator, decimalPrecision, ret.sign)
 	if err != nil {
 		return nil, err
 	}
-	ret.core = core
-	tail, err := computeTail(p, v, g, d)
+	ret.stringOut = stringOut
+	//ret.head = computeHead(trunc)
```
Comment (joshuanario) [inline digits.go]: nit: Delete this inline comment

File: digitsGroup_test.go [hunk 21]
```diff
@@ -0,0 +1,76 @@
...
+
+func Test_ZeroTriplefy(t *testing.T) {
+	//TODO: flesh this out in stimulus
+	for _, testCase := range testCases {
+		sut := zeroTriplefy(testCase.stimulus.value, testCase.stimulus.groupingCharStr)
+		if sut != testCase.output.triplified {
+			t.Fail()
+		}
+	}
+}
```
Comment (joshuanario) [inline digitsGroup_test.go]: nit: These test cases probably don't bring much value.  Just delete this commented block.

Comment (RourkeDawson) [reply digitsGroup_test.go]: this was mentioned in [38305aa](https://github.com/joshuanario/digits/pull/6/commits/38305aad36b7a8eb933fb8470e1b3b01610d7c20). I can go ahead and remove them, but mostly they were failing given the different direction we took the compute functions. they would be relevant for main in it's current state.

I'll make a commit to remove that test file, and we can always revisit it if needed.

Comment (RourkeDawson) [reply digitsGroup_test.go]: [f5c601c](https://github.com/joshuanario/digits/pull/6/commits/f5c601c1871e252d262cdbe3d035880c5030323c)

File: digits.go (hunk 20 above)
Comment (RourkeDawson) [reply digits.go]: [f5c601c](https://github.com/joshuanario/digits/pull/6/commits/f5c601c1871e252d262cdbe3d035880c5030323c)

**Comment by joshuanario** [comment]
> Benchmark for [main](https://github.com/joshuanario/digits/tree/main):
> 
> * 14472 op * 83270 ns/op = 1,204,968,240 ns (1.2 seconds per operation)
> 
> Benchmark for [bug/2](https://github.com/joshuanario/digits/tree/bug/2):
> 
> * 22197 op * 54014 ns/op = 1,198,560,758 ns (1.2 seconds per operation)
> 
> In terms of nanoseconds per operation, the bug branch is slightly more efficient, as it has a lower value. However, the difference is minuscule small. There's likely room to trim some functionality and combine efforts.

I might have explained the benchmark incorrectly.  The important numbers to compare are ns/op, B/op, allocs/op.  The calculations you did are not good measures of performance.  The metrics of concern is how each "op" (or each invocation of the SUT) performed.  Do not aggregate the collected metrics like as the benchmark tool is displaying the averages.  For example, I just ran a benchmark between main and this branch on my local machine and this is what I got.

main:
```
goos: darwin
goarch: arm64
pkg: github.com/joshuanario/digits
BenchmarkSigFigs-10        11980         98881 ns/op       47032 B/op       1972 allocs/op
PASS
ok      github.com/joshuanario/digits   2.166s
```

bug/2
```
goos: darwin
goarch: arm64
pkg: github.com/joshuanario/digits
BenchmarkSigFigs-10        19094         61170 ns/op       28616 B/op       1212 allocs/op
PASS
ok      github.com/joshuanario/digits   2.007s
```

| | ns/op | B/op | allocs/op|
| ----- | ----- | ----- | ----- |
| main | 98,881 | 47,032 | 1,972 |
| bug/2 | 61,170 | 28,616 | 1,212 |
| impact | improved ✅  | improved ✅  | improved ✅  |

I also just ran the functional tests, and they all pass (no regressions and new test coverage for the issue).  👍   And now it looks like this bugfix just made the library waaaaay more performant which is an added bonus. 💪  🏅 💯   Great work @SpencerDawson ! 👏

**Review by joshuanario — CHANGES_REQUESTED** [review]
All test cases pass and the benchmark shows great performance improvement.  There's still some lingering comments that need to be addressed though.

**Comment by RourkeDawson** [comment]
> I might have explained the benchmark incorrectly. The important numbers to compare are ns/op, B/op, allocs/op. The calculations you did are not good measures of performance. The metrics of concern is how each "op" (or each invocation of the SUT) performed. Do not aggregate the collected metrics like as the benchmark tool is displaying the averages. For example, I just ran a benchmark between main and this branch on my local machine and this is what I got.

fair enough. I only have what the benchmark test outputs for me.

**Comment by joshuanario** [comment]
> > I might have explained the benchmark incorrectly. The important numbers to compare are ns/op, B/op, allocs/op. The calculations you did are not good measures of performance. The metrics of concern is how each "op" (or each invocation of the SUT) performed. Do not aggregate the collected metrics like as the benchmark tool is displaying the averages. For example, I just ran a benchmark between main and this branch on my local machine and this is what I got.
> 
> fair enough. I only have what the benchmark test outputs for me.

VS Code collects all three by default.  Not sure why your IDE does not do that.  Please tweak your IDE to collect all three in the future.

**Review by joshuanario — APPROVED** [review]
